os: linux
dist: xenial

language: python

python: 3.7

matrix:
  include:
    - env: CC=gcc
    - env: CC=clang

stages:
  - compile
  - test

install:
  - export NINJA_LATEST=$(curl -s https://api.github.com/repos/ninja-build/ninja/releases/latest | grep browser_download_url | cut -d '"' -f 4 | grep ninja-linux.zip)
  - wget "$NINJA_LATEST"
  - unzip -q ninja-linux.zip -d build
  - export PATH="$PWD/build:$PATH"
  - pip install meson

jobs:
  include:
   - stage: build
     script:
      - meson build --buildtype release
      - ninja -C build
   - stage: test
     script:
      - meson configure -Dbuild_tests=true
      - meson test -v
      - ninja -C build test
  

  
